apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo2
  namespace: namespace2
spec:
  interval: 5m
  dependsOn:
    - name: podinfo1
      namespace: namespace1
  chart:
    spec:
      chart: podinfo
      version: '6.2.0'
      sourceRef:
        kind: HelmRepository
        name: podinfo
