apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo1
  namespace: namespace1
spec:
  interval: 5m
  chart:
    spec:
      chart: podinfo
      version: '6.2.0'
      sourceRef:
        kind: HelmRepository
        name: podinfo
  serviceAccountName: sa-flux
