apiVersion: v1
kind: Pod
metadata:
  name: nginx-pong
  namespace: flux-pong
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
