apiVersion: v1
kind: Pod
metadata:
  name: nginx-ping
  namespace: flux-ping
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
